### PR TITLE
[#998][996] Training bugs

### LINKED ISSUE #998: Minor training bugs
* Can't specify dir for model training data
* Input\output samples can't contain a same name
* dtype index error for some input\output samples

### PR DESCRIPTION
**Pull request by mcdoker18**
* Supported downloading training data from a directory
* Allow a same name for model properties in swagger
* Added cleanup step after robot tests
* Removed "Authorization" header from legion model swagger
* Replaced custom token issuing with keycloak for model deployment

This closes #998 #996 #997

### CODE REVIEW

File: legion/tests/stuff/training_stuff.sh [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+    shift
+    COMMAND=setup
+    ;;
+  cleanup)
+    shift
+    COMMAND=cleanup
+    ;;
+  --models)
+    mapfile -t MODEL_NAMES <<< "${2}"
+    shift
```
Comment (maxkochubey) [inline legion/tests/stuff/training_stuff.sh]: Why two shifts? If we should drop two arguments, we can use `shift 2`.

**Review by maxkochubey — CHANGES_REQUESTED** [review]

File: legion/tests/stuff/training_stuff.sh (hunk 1 above)
Comment (mcdoker18) [reply legion/tests/stuff/training_stuff.sh]: Fixed

**Review by maxkochubey — APPROVED** [review]

**Review by karbyshevds — APPROVED** [review]
